config/routes.rb
Rails.application.routes.draw do
  root 'publications#index'

  resources :publications, only: [:index, :show, :create]
  get 'publications/new/:type' => 'publications#new', as: :new_publication

  resources :authors, only: :index
  resources :rules, only: :index
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  APPLY_RULES_COLUMN_NAME = 'biography'.freeze

  include Taggable
  include Rulable

  validates :name, presence: true
end

app/models/concerns/rulable.rb
module Rulable
  extend ActiveSupport::Concern

  included do
    after_commit :apply_rules, on: :create
  end

  private

    def apply_rules
      ApplyRulesJob.perform_now(self.class, id)
    end
end

app/models/concerns/taggable.rb
module Taggable
  extend ActiveSupport::Concern

  included do
    has_many :taggings, as: :taggable
    has_many :tags, through: :taggings
  end
end

app/models/publication.rb
class Publication < ApplicationRecord
  APPLY_RULES_COLUMN_NAME = 'content'.freeze

  include Taggable
  include Rulable

  belongs_to :author

  validates :title, :type, presence: true

  # @param value [String] `Publication::Poem` or `poem`
  def type=(value)
    klass = begin
              value.constantize
            rescue NameError
              "publication/#{value}".classify.constantize
            end

    write_attribute(:type, klass.to_s)
  end
end

app/models/publication/poem.rb
class Publication::Poem < Publication
  alias_attribute :metaphor, :description
end

app/models/publication/short_story.rb
class Publication::ShortStory < Publication
end

app/models/rule.rb
class Rule < ApplicationRecord
  MAX_COUNT = 20

  belongs_to :tag

  validates :keyword, presence: true, uniqueness: true
  validate :validate_count, on: :create

  scope :ordered, -> { order(id: :desc) }

  private

    def validate_count
      return if self.class.count < MAX_COUNT

      errors.add(:base, "only #{MAX_COUNT} rules allowed")
    end
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :taggings
  has_many :publications, through: :taggings, source: :taggable,
           source_type: 'Publication'
  has_many :authors, through: :taggings, source: :taggable,
           source_type: 'Author'

  validates :name, presence: true, uniqueness: true
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :tag
  belongs_to :taggable, polymorphic: true

  validates :tag_id, uniqueness: { scope: [:taggable_type, :taggable_id] }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def index
    @authors = Author.includes(:tags).order(id: :desc).all
  end
end

app/controllers/publications_controller.rb
class PublicationsController < ApplicationController
  before_action :set_type, only: [:new, :create]
  before_action :set_rules, only: [:new, :create]

  def index
    @publications = Publication.includes(:tags).order(id: :desc).all
  end

  def show
    @publication = PublicationDecorator.new(
      Publication.find(params[:id])
    )
  end

  def new
    @publication = publication_klass.new
  end

  def create
    @publication = publication_klass.new(publication_params)

    if @publication.save
      redirect_to root_path, notice: 'Publication has been successfully created.'
    else
      flash.now[:alert] = @publication.errors.full_messages.first
      render :new
    end
  end

  private

    def publication_params
      params.require(:publication)
            .permit(:title, :content, :author_id, :description, :metaphor)
    end

    def set_type
      @type = params.dig(:publication, :type) || params.dig(:type)
    end

    def set_rules
      @rules = Rule.includes(:tag).ordered.all
    end

    def publication_klass
      "publication/#{@type}".classify.constantize
    end
end

app/controllers/rules_controller.rb
class RulesController < ApplicationController
  def index
    @rules = Rule.includes(:tag).ordered.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/authors/index.html.haml
%h1.m-b-3
  Authors
- @authors.each do |author|
  .m-b-3
    %h4.m-b-1
      = author.name
    .m-b-1
      = author.biography
    .m-b-1
      = render 'shared/tags', obj: author

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Inspire
    = csrf_meta_tags
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'
  %body
    %nav.navbar.navbar-full.navbar-dark.bg-primary.p-y-1
      .container
        = link_to 'Poems & Short Stories', root_path, class: 'navbar-brand'
        %ul.nav.navbar-nav.pull-xs-right
          %li.nav-item
            = link_to 'Publications', root_path, class: 'nav-link'
          %li.nav-item
            = link_to 'Authors', authors_path, class: 'nav-link'
          %li.nav-item
            = link_to 'Rules', rules_path, class: 'nav-link'
          %li.nav-item
            .btn-group
              = link_to 'New Poem', new_publication_path(:poem), class: 'btn btn-success'
              = link_to 'New Story', new_publication_path(:short_story), class: 'btn btn-danger'
    .container.p-y-3
      - if flash[:alert] || notice.present?
        .p-b-2
          - if flash[:alert]
            = render 'shared/notification', message: alert, type: 'danger'
          - if notice.present?
            = render 'shared/notification', message: notice, type: 'success'
      = yield

app/views/publications/_form.html.haml
= form_for @publication, url: publications_path, as: :publication do |f|
  = f.hidden_field :type, value: @type
  .form-group
    = f.label :title
    = f.text_field :title, class: 'form-control'
  .form-group
    = f.label :content
    = f.text_area :content, class: 'form-control'
  .form-group
    = f.label :author
    = f.select :author_id, Author.all.collect { |a| [a.name, a.id] }, {},
      class: 'form-control'
  .form-group
    = render "publications/#{@type}/form", f: f
  .form-group
    = f.submit 'Submit', class: 'btn btn-primary'

app/views/publications/_tags.html.haml
- publication.tags.each do |tag|
  %span.label.label-default
    = tag.name

app/views/publications/index.html.haml
%h1.m-b-3
  Publications
- @publications.each_slice(3) do |publications_group|
  .row.m-b-1
    - publications_group.each do |publication|
      .col-md-4
        .card
          .card-block
            %h4.card-title
              = link_to publication.title, publication_path(publication)
            .card-text
              = publication.content
          - if publication.tags.any?
            .card-footer
              = render 'shared/tags', obj: publication

app/views/publications/new.html.haml
.row
  .col-xs-8
    %h1.m-b-3
      = "New #{@publication&.model_name&.human&.titleize}"
    = render 'form'
  .col-xs-4
    %h4.m-b-2
      Rules
    = render 'rules/list', rules: @rules

app/views/publications/poem/_form.html.haml
= f.label :metaphor
= f.text_area :metaphor, class: 'form-control'

app/views/publications/poem/_show.html.haml
%h5
  Metaphor:
%blockquote.blockquote.text-muted
  = publication.metaphor

app/views/publications/short_story/_form.html.haml
= f.label :description
= f.text_area :description, class: 'form-control'

app/views/publications/short_story/_show.html.haml
%h5
  Description:
%blockquote.blockquote.text-muted
  = publication.description

app/views/publications/show.html.haml
%h1.m-b-1
  = @publication.title
.m-b-1
  = @publication.content
.m-b-1
  = @publication.signature
.m-b-1
  = render 'shared/tags', obj: @publication
.m-b-1
  = render "publications/#{@publication.type.demodulize.underscore}/show",
           publication: @publication

app/views/publications/type/_poem.html.haml
%h5
  Metaphor:
%blockquote.blockquote.text-muted
  = publication.metaphor

app/views/publications/type/_short_story.html.haml
%h5
  Description:
%blockquote.blockquote.text-muted
  = publication.description

app/views/rules/_list.html.haml
%table.table
  %thead
    %tr
      %th
        Keyword
      %th
        Tag
  - rules.each do |rule|
    %tr
      %td
        = rule.keyword
      %td
        = render 'shared/tag', tag: rule.tag

app/views/rules/index.html.haml
%h1.m-b-3
  Rules
= render 'list', rules: @rules

app/views/shared/_notification.html.haml
.alert.alert-dismissible.fade.in.m-b-1{ :class => "alert-#{ type }" }
  = message

app/views/shared/_tag.html.haml
%span.label.label-default
  = tag.name

app/views/shared/_tags.html.haml
- obj.tags.each do |tag|
  = render 'shared/tag', tag: tag